const dataset = {
  postData: [
    {
      title: "সূরা ইখলাস",
      english: "Surah Al-Ikhlas emphasizes the concept of monotheism in Islam.",
      arabic: "قُلْ هُوَ ٱللَّهُ أَحَدٌ",
      bangla: "বল, তিনি আল্লাহ, একমাত্র।",
      category: "quran",
      tags: ["monotheism", "tauheed", "quran"],
      author: "admin",
      slug: "surah-ikhlas",
      status: "published",
      views: 150,
    },
    {
      title: "নিয়ত অনুযায়ী প্রতিফল",
      english: "Actions are judged by intentions.",
      arabic: "إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ",
      bangla: "নিয়ত অনুযায়ীই কাজের ফলাফল নির্ধারিত হয়।",
      category: "hadith",
      tags: ["niyyah", "intention", "hadith"],
      author: "nafi",
      slug: "actions-intentions",
      status: "published",
      views: 95,
    },
    {
      title: "ঋণ সম্পর্কিত ফতোয়া",
      english: "It's prohibited to delay repaying a debt if one is capable.",
      arabic: "مَطْلُ الْغَنِيِّ ظُلْمٌ",
      bangla: "ধনী ব্যক্তির ঋণ ফেরত দিতে গড়িমসি করা অন্যায়।",
      category: "fatwa",
      tags: ["loan", "debt", "justice"],
      author: "mufti-siraj",
      slug: "debt-fatwa",
      status: "draft",
      views: 43,
    },
    {
      title: "সূরা কাওসার",
      english: "Surah Al-Kawthar speaks of Allah's blessings upon the Prophet.",
      arabic: "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ",
      bangla: "নিশ্চয়ই আমি তোমাকে কাওসার দান করেছি।",
      category: "quran",
      tags: ["blessings", "kawthar", "prophet"],
      author: "admin",
      slug: "surah-kawthar",
      status: "published",
      views: 120,
    },
    {
      title: "বুখারীর হাদিস",
      english:
        "The most beloved action to Allah is the most regular and constant even if it were little.",
      arabic: "أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ أَدْومُهَا وَإِنْ قَلَّ",
      bangla:
        "আল্লাহর কাছে সবচেয়ে প্রিয় কাজ হল নিয়মিত এবং অবিচলিত, এমনকি তা ছোট হলেও।",
      category: "bukhari",
      tags: ["consistency", "action", "bukhari"],
      author: "imam-bukhari",
      slug: "beloved-action",
      status: "published",
      views: 88,
    },
    {
      title: "মুসলিমের হাদিস",
      english:
        "A true Muslim is one from whose tongue and hands other Muslims are safe.",
      arabic: "المسلم من سلم المسلمون من لسانه ويده",
      bangla:
        "সত্যিকারের মুসলিম হল সেই ব্যক্তি যার জিহ্বা ও হাত থেকে অন্য মুসলিমরা নিরাপদ থাকে।",
      category: "muslim",
      tags: ["safety", "behavior", "muslim"],
      author: "imam-muslim",
      slug: "true-muslim",
      status: "published",
      views: 110,
    },
  ],
};

module.exports = dataset;
